// <auto-generated />
using System;
using Airbnb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airbnb.Migrations
{
    [DbContext(typeof(AirBnbContext))]
    [Migration("20251101150127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Airbnb.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "San Francisco"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Dallas"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Boston"
                        });
                });

            modelBuilder.Entity("Airbnb.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservation");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            ReservationEndDate = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 1
                        },
                        new
                        {
                            ReservationId = 2,
                            ReservationEndDate = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 2
                        },
                        new
                        {
                            ReservationId = 3,
                            ReservationEndDate = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 3
                        });
                });

            modelBuilder.Entity("Airbnb.Models.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BathroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PricePerNight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidencePicture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.ToTable("Residence");

                    b.HasData(
                        new
                        {
                            ResidenceId = 1,
                            BathroomNumber = 1,
                            BedroomNumber = 1,
                            GuestNumber = 3,
                            LocationId = 1,
                            Name = "Golden Gate Condo",
                            PricePerNight = "140",
                            ResidencePicture = "GoldenGate.png"
                        },
                        new
                        {
                            ResidenceId = 2,
                            BathroomNumber = 2,
                            BedroomNumber = 2,
                            GuestNumber = 5,
                            LocationId = 2,
                            Name = "LA Downtown Loft",
                            PricePerNight = "180",
                            ResidencePicture = "LaDowntown.png"
                        },
                        new
                        {
                            ResidenceId = 3,
                            BathroomNumber = 2,
                            BedroomNumber = 3,
                            GuestNumber = 7,
                            LocationId = 3,
                            Name = "Dallas Ranch Home",
                            PricePerNight = "90",
                            ResidencePicture = "DallasRanch.png"
                        },
                        new
                        {
                            ResidenceId = 4,
                            BathroomNumber = 1,
                            BedroomNumber = 2,
                            GuestNumber = 4,
                            LocationId = 4,
                            Name = "Boston Harbor Apartment",
                            PricePerNight = "110",
                            ResidencePicture = "BostonHarbor.png"
                        });
                });

            modelBuilder.Entity("Airbnb.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DOB = "03/15/1998",
                            Email = "michael.green@airbnb.com",
                            Name = "Michael Green",
                            PhoneNumber = "201-101-2020"
                        },
                        new
                        {
                            UserId = 2,
                            DOB = "11/22/1999",
                            Email = "sophia.lee@airbnb.com",
                            Name = "Sophia Lee",
                            PhoneNumber = "241-303-4040"
                        },
                        new
                        {
                            UserId = 3,
                            DOB = "08/09/2001",
                            Email = "david.carter@airbnb.com",
                            Name = "David Carter",
                            PhoneNumber = "608-505-6060"
                        });
                });

            modelBuilder.Entity("Airbnb.Models.Reservation", b =>
                {
                    b.HasOne("Airbnb.Models.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("Airbnb.Models.Residence", b =>
                {
                    b.HasOne("Airbnb.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
